# Generated by Django 2.2.3 on 2019-08-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(max_length=240)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(blank=True, default='anonymous', max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='album.Album')),
            ],
        ),
    ]
