# Generated by Django 2.2.3 on 2019-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(blank=True, default='anonymous', max_length=100)),
            ],
            options={
                'ordering': ('-timestamp', '-pk'),
            },
        ),
    ]
